[package]
name = "day-8-seven-segment-search"
version = "0.1.0"
authors = ["Andy Coder <Andy.Coder@ibm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
